import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/context/ProductContext";
import { Toaster } from "sonner";
import Navbar from "@/components/ui/Navbar";
import { CategoryProvider } from "@/context/CategoryContext";
import { Footer } from "@/components/ui/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CategoryProvider>
      <ProductProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <Toaster richColors />
            <section className="section">{children}</section>
            {/* <Footer /> */}
          </body>
        </html>
      </ProductProvider>
    </CategoryProvider>
  );
}
